# Generated by Django 5.1 on 2025-02-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_customuser_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_complete',
        ),
    ]
